import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { AuthProvider } from "@/contexts/AuthContext";
import getCookies from '@/services/getCookies';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Project Auth-JWT',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='h-full bg-white'>
      <body className={inter.className + "h-full"}>
        <AuthProvider>
        {children}
        </AuthProvider>
        
        </body>
    </html>
  )
}
